/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asav_processimage_OpenCVNativeCaller */

#ifndef _Included_com_asav_processimage_OpenCVNativeCaller
#define _Included_com_asav_processimage_OpenCVNativeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asav_processimage_OpenCVNativeCaller
 * Method:    niBlackThreshold
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_asav_processimage_OpenCVNativeCaller_niBlackThreshold
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
